# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9a55116bd113755ba332a57f5e3b50a8309fde8ee10c8f03b4156f90ea9d16a6d261d6e7676814a8dea3ca55bb5d533ad7b291f00bfe9472b20be4c9d6855a6d

test:
  secret_key_base: b2a6fe05a717e14ad4a5d69d3d770edc9610fb53cc158d41586e5b0a17961212cad4fb88bde84e7a60431f0e7cc0dcccf3b829ada62b7cd49161e1e33f32e9b9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
